
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 704982
	#The name of the modpack
	modpackName = "M-Tech"
	#The version of the modpack
	modpackVersion = "1.3.15"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

